/**************************THIS FILE WAS AUTOGENERATED**************************/
#include <stddef.h>
static char const *user_argv[] = {"737873545250", "-n", "200", "-s", "250", NULL};
static const int user_argc = 5;
/*******************************************************************************/