/**************************THIS FILE WAS AUTOGENERATED**************************/
#include <stddef.h>
static char const *user_argv[] = {"10511010511510512052116119111", "0", NULL};
static const int user_argc = 2;
/*******************************************************************************/